[features]
seeds = false
skip-lint = false

[programs.localnet]
dynamic_bonding_curve = "4p6rpELnszFn51S5C9s5KfT8Pf1zDeyLWSp3Bs56fE9B"

[programs.devnet]
dynamic_bonding_curve = "4p6rpELnszFn51S5C9s5KfT8Pf1zDeyLWSp3Bs56fE9B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "keys/devnet/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
ixdata = "yarn run tsx --tsconfig ./tsconfig.json ./scripts/generate_ix_data_for_tests.ts"

[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"
